#!/bin/bash

##Script to generate trees

#SBATCH -p normal                
#SBATCH -c 8                     
#SBATCH --mem=6GB
#SBATCH --job-name fsc2709-ex04                
#SBATCH -o %j.out              
#SBATCH -e %j.err

# modules
module load iq-tree

# iqtree model 0
cd ../input_files/DNA_for_predictive/ppgcourse_model0
FILES="*.arp"

for f in $FILES
do
	grep "^[0-9]" $f | perl -p -e  's/^/>/g' |  perl -p -e 's/\t[0-9]+//g' | perl -p -e 's/\t/\r/g' > model0.fas
        iqtree -s model0.fas -pre $f -nt 8 -redo
done


# iqtree model 1
cd ../input_files/DNA_for_predictive/ppgcourse_model1
FILES="*.arp"

for f in $FILES
do
	grep "^[0-9]" $f | perl -p -e  's/^/>/g' |  perl -p -e 's/\t[0-9]+//g' | perl -p -e 's/\t/\r/g' > model1.fas
        iqtree -s model1.fas -pre $f -nt 8 -redo
done

