#!/bin/bash

# define names
#SBATCH --job-name=trinityQC
#SBATCH --error trinityQC-%j.err
#SBATCH --output trinityQC-%j.out

# memory and CPUs request
#SBATCH --mem=6G
#SBATCH --cpus-per-task=8

# module load
module load Trinity

# jobs to launch
/opt/ohpc/pub/eb/software/Trinity/2.10.0-foss-2019b-Python-3.7.4/trinityrnaseq-v2.10.0/util/TrinityStats.pl ./4trinity/Trinity.fasta > ./6QC_trinity/Trinity_assembly.metrics
/opt/ohpc/pub/eb/software/Trinity/2.10.0-foss-2019b-Python-3.7.4/trinityrnaseq-v2.10.0/util/TrinityStats.pl ./5cdhit/Trinity_cdhit.fasta > ./6QC_trinity/Trinity_cdhit_assembly.metrics

